apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  labels:
    app: redis
spec:
  storageClassName: openebs-host
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi