apiVersion: v1
kind: Service
metadata:
  name: tor
  labels:
    app: tor
spec:
  type: ClusterIP
  ports:
    - port: 9050
      name: torproxy
    - port: 9051
      name: torcontrol
  selector:
    app: tor