apiVersion: apps/v1
kind: Deployment
metadata:
  name: follow-invoices
  labels:
    app: follow-invoices
spec:
  selector:
    matchLabels:
      app: follow-invoices
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: follow-invoices
    spec:
      containers:
        - name: follow-invoices
          image: recksato/robosats:534e4c0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "1000m"
              memory: "500Mi"
            requests:
              cpu: "10m"
              memory: "50Mi"
          envFrom:
            - configMapRef:
                name: robosats-configmap
            - secretRef:
                name: robosats-secret
            - secretRef:
                name: postgres-secret # Using the Secret postgres-secret
          command: ["python3", "manage.py", "follow_invoices"] 
          volumeMounts:
            - name: lnd-data
              mountPath: /lnd
      volumes:
        - name: lnd-data
          persistentVolumeClaim:
            claimName: lnd-pvc          