apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lnd-pvc
  labels:
    app: lnd
spec:
  storageClassName: openebs-host
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi