apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litd-pvc
  labels:
    app: litd
spec:
  storageClassName: openebs-host
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi