# Secret postgres-secret for the postgres app
# Define default database name, user, and password
# Use: echo -n 'super-secret-password' | base64
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_DB: cm9ib3NhdHMtZGI= # robosats-db
  POSTGRES_USER: YWRtaW4= # admin
  POSTGRES_PASSWORD: MTIzNDU2NzhzdHJvbmdwYXNzd29yZA== # 12345678strongpassword