apiVersion: v1
kind: Service
metadata:
  name: i2p-external
  labels:
    app: i2p
spec:
  type: NodePort
  ports:
    - name: router-control
      nodePort: 30657
      port: 7657
  selector:
    app: i2p
---
apiVersion: v1
kind: Service
metadata:
  name: i2p-cluster
  labels:
    app: i2p
spec:
  type: ClusterIP
  ports:
    - name: sam-bridge
      port: 7656
      targetPort: 7656
  selector:
    app: i2p