apiVersion: v1
kind: Service
metadata:
  name: nginx-external
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 30080
      port: 80
  selector:
    app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: nginx