apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: static-pvc # Sets name of PV
  labels:
    app: static # Defines app to create PVC for
spec:
  storageClassName: openebs-host
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 2Gi # Sets PVC's size