apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    app: celery-worker
spec:
  selector:
    matchLabels:
      app: celery-worker
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: recksato/robosats:534e4c0
          # imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "1000m"
              memory: "500Mi"
            requests:
              cpu: "10m"
              memory: "50Mi"
          envFrom:
            - configMapRef:
                name: robosats-configmap
            - secretRef:
                name: robosats-secret
            - secretRef:
                name: postgres-secret # Using the Secret postgres-secret
          command: ["celery", "-A", "robosats", "worker", "--loglevel=INFO"]
          # ports:
          #   - containerPort: 8000
      #     volumeMounts:
      #       - name: lnd-data
      #         mountPath: /lnd
      # volumes:
      #   - name: lnd-data
      #     persistentVolumeClaim:
      #       claimName: lnd-pvc