apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    k8s-app: kube-dns
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
      errors
      health {
        lameduck 5s
      }
      ready

      log . {
        class error
      }
      kubernetes cluster.local in-addr.arpa ip6.arpa {
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
      }
      # These are the only IPs containers can make requests to (hard-coded DNS)
      hosts {
        149.154.167.99 telegram.org
        149.154.167.99 core.telegram.org
        149.154.167.99 api.telegram.org
        104.16.145.212 blockchain.info
        165.22.7.101 api.yadio.io

        ...
        fallthrough
      }
      prometheus :9153
      forward . 8.8.8.8 8.8.4.4 
      cache 30
      loop

      reload
      loadbalance
    }