apiVersion: v1
kind: Secret
metadata:
  name: robosats-secret
data:
  LND_CERT_BASE64: a # Your LND BASE64 TLS CERT encoded as secret
  LND_MACAROON_BASE64: b # Your LND MACAROON BASE64 encoded as secret
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLTZeJjZ1dyRiNV5lbiUoY3Uya2M3X28pKG1ncGF6eCNqX3pud2x5bTB2eGZhbW4ydW8tCa== # 'django-insecure-6^&6uw$b5^en%(cu2kc7_o)(mgpazx#j_znwlym0vxfamn2uu-'
  TELEGRAM_TOKEN: d # Your Telegram Bot Token encoded as secret