apiVersion: v1
kind: Service
metadata:
  name: bitcoind
  labels:
    app: bitcoind
spec:
  type: ClusterIP
  ports:
    - name: rpc
      port: 18332 # mainnet 8332
    - name: peers
      port: 18333 # mainnet 8333
    - name: block-events
      port: 18501
    - name: tx-events
      port: 18502
  selector:
    app: bitcoind