version: '3.9'
services:
  robosats:
    build: .
    image: recksato/robosats-web:latest
    container_name: robosats
    restart: always
    network_mode: service:tor
    volumes:
      - ./serve_misc:/serve_misc/
      - ./custom_nginx.conf:/etc/nginx/nginx.conf
  tor:
    build: ../compose/tor
    container_name: tor
    restart: always
    environment:
      LOCAL_USER_ID: 1000
      LOCAL_GROUP_ID: 1000
    ports:
      - 80:80
    volumes:
      - ./tor:/var/lib/tor
      - ./torrc:/etc/tor/torrc